// Media manifest: types (brief §9.2, frozen) + loader. Owner: A5.
// manifest.json is GENERATED by pipeline/build_manifest.py; never edit it by hand.
//
// Paths inside manifest.json are relative to the site root ("media/plans/plan-b40.av1.mp4"). Everything
// exported here goes through mediaUrl(): document-relative for the root base ('/' or './', identical in the
// prerender and the client), prefixed only for a real sub-path base, so components can use the strings
// directly in src/poster/href attributes.
//
// Conventions
// - Videos: sources[0] is AV1 (first, for headless Chromium and modern browsers), sources[1] is H.264.
//   `type` carries the exact codecs string measured from the file. Every video has `poster` (AVIF) and
//   `posterFallback` (JPEG; use it for <video poster> where AVIF support is uncertain, e.g. old Safari).
// - Images: sources = [AVIF, JPEG] for <picture>; the last source is the <img src> fallback.
// - `loop: null` means play once and hold the last frame. When set, {in, out} are seconds; the encoded file
//   already carries the crossfaded seam, so a plain `loop` attribute is correct.
// - Phone variants are separate ids with the suffix "-m" (plan-b40-m, arena-0104-m, el-c30-m) or "-916"
//   (the phone hero set). Use `phoneVariant(id)` to resolve one.
// - `bytes` maps each file path (resolved, as in sources/poster) to its size in bytes.
// - Hero: `hero-snap-169.stills` = { av1, h264 } freeze stills matched by video.currentSrc; `freezeFrame`
//   is the source frame number in c34 (84; the film's last frame); `meta` points at hero-meta-169.json.
// - Plans: `borderRect` = [x0, y0, x1, y1] of the yellow bay border, normalised 0..1 of the plan frame
//   (all registered plans share 120..1320 of 1440 = 0.0833..0.9167). plan-b44 / plan-b44-260 also carry
//   `lineEndpoints` (the freshly snapped line, normalised, for the plan-cut registration).
// - `mock: true` on the root marks the first-wave placeholder manifest.
import raw from './manifest.json';

export type Src = { src: string; type: string };
export type ViewKind = 'film' | 'frame' | 'still' | 'depth' | 'drawing';
export type MediaKind = 'video' | 'image' | 'depth' | 'matte' | 'json' | 'svg' | 'pdf' | 'bin';

export type MediaEntry = {
  id: string;
  kind: MediaKind;
  sources?: Src[];
  poster?: string;
  /** JPEG twin of `poster` (extension to §9.2, optional). */
  posterFallback?: string;
  w: number;
  h: number;
  dur?: number;
  fps?: number;
  /** null = play once and hold the last frame. */
  loop?: { in: number; out: number } | null;
  /** Hero freeze stills, matched by video.currentSrc. */
  stills?: { av1: string; h264: string };
  alt: string;
  /** `id` (when set) is the key in src/content/viewTitles.ts VIEW_TITLES; hasntHappened/oneFrame mirror that table. */
  viewTitle: { view: string; kind: ViewKind; suffix?: string; id?: string; hasntHappened?: boolean; oneFrame?: boolean };
  borderRect?: [number, number, number, number];
  lineEndpoints?: [[number, number], [number, number]];
  freezeFrame?: number;
  /** URL of a JSON sidecar (hero meta, lines, proof). */
  meta?: string;
  /** the-set-169 only: poster alt, WebVTT captions and the transcript file (resolved URLs). */
  posterAlt?: string;
  captions?: string;
  transcript?: string;
  /** t7-proof only (A6-2): the measured detection label from t7-proof.json, null while unmeasured/mock. */
  proof?: { smallestLabel: string | null; pass: boolean } | null;
  bytes: Record<string, number>;
};

type RawManifest = {
  version: number;
  mock?: boolean;
  generated?: string;
  media: Record<string, MediaEntry>;
  sheetVideoPriority: Record<string, string[]>;
};

const BASE: string = (import.meta.env && import.meta.env.BASE_URL) || '/';

/** Resolve a manifest-relative path ("media/…") against the site base. Absolute URLs pass through. */
export function mediaUrl(path: string): string {
  if (/^([a-z]+:)?\/\//i.test(path) || path.startsWith('/') || path.startsWith('data:')) return path;
  // requests/A6-4: '/' (prerender and dev) and './' (client build) both mean the site root. Keep the path
  // document-relative ('media/…') so server and client render identical attributes (no hydration
  // mismatch) and the site still works from a sub-folder. Only a real sub-path base is prefixed.
  if (BASE === '/' || BASE === './' || BASE === '') return path;
  return (BASE.endsWith('/') ? BASE : BASE + '/') + path;
}

function resolveEntry(e: MediaEntry): MediaEntry {
  const bytes: Record<string, number> = {};
  for (const [k, v] of Object.entries(e.bytes || {})) bytes[mediaUrl(k)] = v;
  return {
    ...e,
    sources: e.sources?.map((s) => ({ src: mediaUrl(s.src), type: s.type })),
    poster: e.poster ? mediaUrl(e.poster) : undefined,
    posterFallback: e.posterFallback ? mediaUrl(e.posterFallback) : undefined,
    stills: e.stills ? { av1: mediaUrl(e.stills.av1), h264: mediaUrl(e.stills.h264) } : undefined,
    meta: e.meta ? mediaUrl(e.meta) : undefined,
    captions: e.captions ? mediaUrl(e.captions) : undefined,
    transcript: e.transcript ? mediaUrl(e.transcript) : undefined,
    bytes,
  };
}

const manifest = raw as unknown as RawManifest;

export const isMockManifest: boolean = !!manifest.mock;

export const media: Record<string, MediaEntry> = Object.fromEntries(
  Object.entries(manifest.media).map(([id, e]) => [id, resolveEntry(e)]),
);

/** Per sheet: video ids in playback priority order (VideoManager plays the top two visible). */
export const sheetVideoPriority: Record<string, string[]> = manifest.sheetVideoPriority;

export function hasMedia(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(media, id);
}

/** Throws in dev if the id is unknown, so typos surface immediately. */
export function getMedia(id: string): MediaEntry {
  const e = media[id];
  if (!e) throw new Error(`media: unknown id "${id}"`);
  return e;
}

/** The phone variant of an id if the manifest has one ("plan-b40" → "plan-b40-m", "hero-snap-169" → "hero-snap-916"). */
export function phoneVariant(id: string): string {
  const cands = [id + '-m', id.replace(/-169(?=$|-)/, '-916')];
  for (const c of cands) if (c !== id && hasMedia(c)) return c;
  return id;
}

/** Pick the hero freeze still that matches the codec the <video> actually chose. */
export function freezeStillFor(entry: MediaEntry, currentSrc: string): string | undefined {
  if (!entry.stills) return undefined;
  return /h264|avc/i.test(currentSrc) ? entry.stills.h264 : entry.stills.av1;
}

/** Fetch a JSON sidecar (hero meta, lines-b44, t7-proof). */
export async function loadJson<T = unknown>(idOrUrl: string): Promise<T> {
  const url = hasMedia(idOrUrl) ? (media[idOrUrl].sources?.[0]?.src ?? media[idOrUrl].meta ?? '') : idOrUrl;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`media: ${url} ${r.status}`);
  return (await r.json()) as T;
}

/** Fetch a binary depth grid (hero-depth-169 / hero-depth-916) as little-endian Uint16 samples. */
export async function loadDepthGrid(id: string): Promise<Uint16Array> {
  const e = getMedia(id);
  const r = await fetch(e.sources![0].src);
  if (!r.ok) throw new Error(`media: ${id} ${r.status}`);
  const buf = await r.arrayBuffer();
  const dv = new DataView(buf);
  const out = new Uint16Array(buf.byteLength >> 1);
  for (let i = 0; i < out.length; i++) out[i] = dv.getUint16(i * 2, true);
  return out;
}
