// A-200 · CONTEXT · THE 1811 GRID (brief 3.9, 4.4). Owner: A4.
//
// One pinned stage (200vh desktop, 180vh phone: a 100vh / 80vh pin). Re-timed inside the same pin so no
// screen is empty (FIXLIST-1 F-043; PRODUCTION_PLAN review-1 overrides). p = stage progress:
//   0.00–0.12  the row poster (five bays, laid out with A-100's geometry: full content width, b = W/5.4,
//              gap 0.1 b, from the spine) turns to its pencil outline, "THE FIVE BAYS · ILLUSTRATIVE"
//   0.12–0.20  the outline morphs into a scalloped orange HOLD cloud (24 cubic segments each, authored by
//              pipeline/grid1811.mjs); its tag "VENUE: HOLD — Venue to be announced on this site." is in by 0.18
//              (the bays label hands over to it, both readable, over 0.16–0.19)
//   0.20–0.40  the cloud holds, tag readable (20vh desktop, 16vh phone)
//   0.40–0.50  it lifts (shadow 2 → 6 px) and flies (FLIP) into the title strip's VENUE cell, which pulses
//              once; the tag stays on it until 0.48. Phones: it settles on the static tag under the legend.
//   0.40–0.86  a SEPARATE drawing: the frame strokes on from its top-right corner (0.40–0.52), the caption
//              prints at 0.45, and the 1811 grid module draws outward from its centre through a radial mask
//              (0.42–0.80; its black ground grows with it, so there is never an empty box); TRUE NORTH, the
//              grid's own north arrow and the angle arc draw on (0.70–0.86)
//   0.55       H2 and body print (desktop ≥1024 px: in the left columns, beside the drawing)
//   0.85       the statement prints
// Rule 2: the bays, the row outline and the cloud are never drawn on the grid. The grid's lines start at a
// zero radius at its own vertex and the reveal eases in, so the cloud has left that area before any street
// line is drawn; the grid is its own figure with its own title. A jump (INDEX) lands at p = 0.88 on desktop:
// the finished frame, H2 on screen.
// No JS, reduced motion, MOTION OFF: no pin; the HOLD tag on its own, then the static grid diagram.
// Every per-frame write goes to refs (style / attributes); React never re-renders on scroll.

import { useCallback, useEffect, useRef, type CSSProperties } from 'react';
import { useStageProgress } from '../system/useStageProgress';
import { registerCaptureScene } from '../system/capture';
import { settleEase, drawEase, segment } from '../system/easing';
import { onLayout } from '../system/scroll';
import { ViewTitle } from '../chrome/ViewTitle';
import { SheetTag } from '../chrome/SheetTag';
import { titleStrip } from '../chrome/titleStrip';
import { Picture } from '../system/Picture';
import { NorthArrow } from '../marks/NorthArrow';
import { AngleArc } from '../marks/AngleArc';
import { HoldCloud } from '../marks/HoldCloud';
import { A200, a200Body } from '../content/copy/a104-a200';
import { useLive, useWidth, useMediaQuery, mixHex, lerp, PAL, frames } from './a4/util';
import './a4/a4.css';

// <grid1811> generated by pipeline/grid1811.mjs, do not edit by hand
const GEN = {"row":{"w":1890,"h":350},"bays":"M0 0H350V350H0ZM385 0H735V350H385ZM770 0H1120V350H770ZM1155 0H1505V350H1155ZM1540 0H1890V350H1540Z","outline":[0,0,63,0,126,0,189,0,252,0,315,0,378,0,441,0,504,0,567,0,630,0,693,0,756,0,819,0,882,0,945,0,1008,0,1071,0,1134,0,1197,0,1260,0,1323,0,1386,0,1449,0,1512,0,1575,0,1638,0,1701,0,1764,0,1827,0,1890,0,1890,58.3,1890,116.7,1890,175,1890,233.3,1890,291.7,1890,350,1827,350,1764,350,1701,350,1638,350,1575,350,1512,350,1449,350,1386,350,1323,350,1260,350,1197,350,1134,350,1071,350,1008,350,945,350,882,350,819,350,756,350,693,350,630,350,567,350,504,350,441,350,378,350,315,350,252,350,189,350,126,350,63,350,0,350,0,291.7,0,233.3,0,175,0,116.7,0,58.3,0,0],"cloud":[40,30,25.5,-46,235.5,-46,221,30,206.5,-46,416.5,-46,402,30,387.5,-46,597.5,-46,583,30,568.5,-46,778.5,-46,764,30,749.5,-46,959.5,-46,945,30,930.5,-46,1140.5,-46,1126,30,1111.5,-46,1321.5,-46,1307,30,1292.5,-46,1502.5,-46,1488,30,1473.5,-46,1683.5,-46,1669,30,1654.5,-46,1864.5,-46,1850,30,1910.9,18.4,1910.9,186.6,1850,175,1910.9,163.4,1910.9,331.6,1850,320,1864.5,396,1654.5,396,1669,320,1683.5,396,1473.5,396,1488,320,1502.5,396,1292.5,396,1307,320,1321.5,396,1111.5,396,1126,320,1140.5,396,930.5,396,945,320,959.5,396,749.5,396,764,320,778.5,396,568.5,396,583,320,597.5,396,387.5,396,402,320,416.5,396,206.5,396,221,320,235.5,396,25.5,396,40,320,-20.9,331.6,-20.9,163.4,40,175,-20.9,186.6,-20.9,18.4,40,30],"cloudBox":[-20.9,-46,1910.9,396],"view":{"w":1000,"h":800},"vertex":{"x":500,"y":430},"angle":29,"fieldR":680.3,"thin":"M-651.7 -389.5H-532M-651.7 -351.5H-532M-651.7 -340.1H-532M-651.7 -302.1H-532M-651.7 -290.7H-532M-651.7 -252.7H-532M-651.7 -241.3H-532M-651.7 -203.3H-532M-651.7 -191.9H-532M-651.7 -153.9H-532M-651.7 -142.5H-532M-651.7 -104.5H-532M-651.7 -93.1H-532M-651.7 -55.1H-532M-651.7 -43.7H-532M-651.7 -5.7H-532M-651.7 5.7H-532M-651.7 43.7H-532M-651.7 55.1H-532M-651.7 93.1H-532M-651.7 104.5H-532M-651.7 142.5H-532M-651.7 153.9H-532M-651.7 191.9H-532M-651.7 203.3H-532M-651.7 241.3H-532M-651.7 252.7H-532M-651.7 290.7H-532M-651.7 302.1H-532M-651.7 340.1H-532M-651.7 351.5H-532M-651.7 389.5H-532M-513 -537.7H-397.1M-513 -499.7H-397.1M-513 -488.3H-397.1M-513 -450.3H-397.1M-513 -438.9H-397.1M-513 -400.9H-397.1M-513 -389.5H-397.1M-513 -351.5H-397.1M-513 -340.1H-397.1M-513 -302.1H-397.1M-513 -290.7H-397.1M-513 -252.7H-397.1M-513 -241.3H-397.1M-513 -203.3H-397.1M-513 -191.9H-397.1M-513 -153.9H-397.1M-513 -142.5H-397.1M-513 -104.5H-397.1M-513 -93.1H-397.1M-513 -55.1H-397.1M-513 -43.7H-397.1M-513 -5.7H-397.1M-513 5.7H-397.1M-513 43.7H-397.1M-513 55.1H-397.1M-513 93.1H-397.1M-513 104.5H-397.1M-513 142.5H-397.1M-513 153.9H-397.1M-513 191.9H-397.1M-513 203.3H-397.1M-513 241.3H-397.1M-513 252.7H-397.1M-513 290.7H-397.1M-513 302.1H-397.1M-513 340.1H-397.1M-513 351.5H-397.1M-513 389.5H-397.1M-513 400.9H-397.1M-513 438.9H-397.1M-513 450.3H-397.1M-513 488.3H-397.1M-513 499.7H-397.1M-513 537.7H-397.1M-378.1 -636.5H-203.3M-378.1 -598.5H-203.3M-378.1 -587.1H-203.3M-378.1 -549.1H-203.3M-378.1 -537.7H-203.3M-378.1 -499.7H-203.3M-378.1 -488.3H-203.3M-378.1 -450.3H-203.3M-378.1 -438.9H-203.3M-378.1 -400.9H-203.3M-378.1 -389.5H-203.3M-378.1 -351.5H-203.3M-378.1 -340.1H-203.3M-378.1 -302.1H-203.3M-378.1 -290.7H-203.3M-378.1 -252.7H-203.3M-378.1 -241.3H-203.3M-378.1 -203.3H-203.3M-378.1 -191.9H-203.3M-378.1 -153.9H-203.3M-378.1 -142.5H-203.3M-378.1 -104.5H-203.3M-378.1 -93.1H-203.3M-378.1 -55.1H-203.3M-378.1 -43.7H-203.3M-378.1 -5.7H-203.3M-378.1 5.7H-203.3M-378.1 43.7H-203.3M-378.1 55.1H-203.3M-378.1 93.1H-203.3M-378.1 104.5H-203.3M-378.1 142.5H-203.3M-378.1 153.9H-203.3M-378.1 191.9H-203.3M-378.1 203.3H-203.3M-378.1 241.3H-203.3M-378.1 252.7H-203.3M-378.1 290.7H-203.3M-378.1 302.1H-203.3M-378.1 340.1H-203.3M-378.1 351.5H-203.3M-378.1 389.5H-203.3M-378.1 400.9H-203.3M-378.1 438.9H-203.3M-378.1 450.3H-203.3M-378.1 488.3H-203.3M-378.1 499.7H-203.3M-378.1 537.7H-203.3M-378.1 549.1H-203.3M-378.1 587.1H-203.3M-378.1 598.5H-203.3M-378.1 636.5H-203.3M-184.3 -685.9H-9.5M-184.3 -647.9H-9.5M-184.3 -636.5H-9.5M-184.3 -598.5H-9.5M-184.3 -587.1H-9.5M-184.3 -549.1H-9.5M-184.3 -537.7H-9.5M-184.3 -499.7H-9.5M-184.3 -488.3H-9.5M-184.3 -450.3H-9.5M-184.3 -438.9H-9.5M-184.3 -400.9H-9.5M-184.3 -389.5H-9.5M-184.3 -351.5H-9.5M-184.3 -340.1H-9.5M-184.3 -302.1H-9.5M-184.3 -290.7H-9.5M-184.3 -252.7H-9.5M-184.3 -241.3H-9.5M-184.3 -203.3H-9.5M-184.3 -191.9H-9.5M-184.3 -153.9H-9.5M-184.3 -142.5H-9.5M-184.3 -104.5H-9.5M-184.3 -93.1H-9.5M-184.3 -55.1H-9.5M-184.3 -43.7H-9.5M-184.3 -5.7H-9.5M-184.3 5.7H-9.5M-184.3 43.7H-9.5M-184.3 55.1H-9.5M-184.3 93.1H-9.5M-184.3 104.5H-9.5M-184.3 142.5H-9.5M-184.3 153.9H-9.5M-184.3 191.9H-9.5M-184.3 203.3H-9.5M-184.3 241.3H-9.5M-184.3 252.7H-9.5M-184.3 290.7H-9.5M-184.3 302.1H-9.5M-184.3 340.1H-9.5M-184.3 351.5H-9.5M-184.3 389.5H-9.5M-184.3 400.9H-9.5M-184.3 438.9H-9.5M-184.3 450.3H-9.5M-184.3 488.3H-9.5M-184.3 499.7H-9.5M-184.3 537.7H-9.5M-184.3 549.1H-9.5M-184.3 587.1H-9.5M-184.3 598.5H-9.5M-184.3 636.5H-9.5M9.5 -685.9H184.3M9.5 -647.9H184.3M9.5 -636.5H184.3M9.5 -598.5H184.3M9.5 -587.1H184.3M9.5 -549.1H184.3M9.5 -537.7H184.3M9.5 -499.7H184.3M9.5 -488.3H184.3M9.5 -450.3H184.3M9.5 -438.9H184.3M9.5 -400.9H184.3M9.5 -389.5H184.3M9.5 -351.5H184.3M9.5 -340.1H184.3M9.5 -302.1H184.3M9.5 -290.7H184.3M9.5 -252.7H184.3M9.5 -241.3H184.3M9.5 -203.3H184.3M9.5 -191.9H184.3M9.5 -153.9H184.3M9.5 -142.5H184.3M9.5 -104.5H184.3M9.5 -93.1H184.3M9.5 -55.1H184.3M9.5 -43.7H184.3M9.5 -5.7H184.3M9.5 5.7H184.3M9.5 43.7H184.3M9.5 55.1H184.3M9.5 93.1H184.3M9.5 104.5H184.3M9.5 142.5H184.3M9.5 153.9H184.3M9.5 191.9H184.3M9.5 203.3H184.3M9.5 241.3H184.3M9.5 252.7H184.3M9.5 290.7H184.3M9.5 302.1H184.3M9.5 340.1H184.3M9.5 351.5H184.3M9.5 389.5H184.3M9.5 400.9H184.3M9.5 438.9H184.3M9.5 450.3H184.3M9.5 488.3H184.3M9.5 499.7H184.3M9.5 537.7H184.3M9.5 549.1H184.3M9.5 587.1H184.3M9.5 598.5H184.3M9.5 636.5H184.3M203.3 -636.5H355.3M203.3 -598.5H355.3M203.3 -587.1H355.3M203.3 -549.1H355.3M203.3 -537.7H355.3M203.3 -499.7H355.3M203.3 -488.3H355.3M203.3 -450.3H355.3M203.3 -438.9H355.3M203.3 -400.9H355.3M203.3 -389.5H355.3M203.3 -351.5H355.3M203.3 -340.1H355.3M203.3 -302.1H355.3M203.3 -290.7H355.3M203.3 -252.7H355.3M203.3 -241.3H355.3M203.3 -203.3H355.3M203.3 -191.9H355.3M203.3 -153.9H355.3M203.3 -142.5H355.3M203.3 -104.5H355.3M203.3 -93.1H355.3M203.3 -55.1H355.3M203.3 -43.7H355.3M203.3 -5.7H355.3M203.3 5.7H355.3M203.3 43.7H355.3M203.3 55.1H355.3M203.3 93.1H355.3M203.3 104.5H355.3M203.3 142.5H355.3M203.3 153.9H355.3M203.3 191.9H355.3M203.3 203.3H355.3M203.3 241.3H355.3M203.3 252.7H355.3M203.3 290.7H355.3M203.3 302.1H355.3M203.3 340.1H355.3M203.3 351.5H355.3M203.3 389.5H355.3M203.3 400.9H355.3M203.3 438.9H355.3M203.3 450.3H355.3M203.3 488.3H355.3M203.3 499.7H355.3M203.3 537.7H355.3M203.3 549.1H355.3M203.3 587.1H355.3M203.3 598.5H355.3M203.3 636.5H355.3M374.3 -537.7H526.3M374.3 -499.7H526.3M374.3 -488.3H526.3M374.3 -450.3H526.3M374.3 -438.9H526.3M374.3 -400.9H526.3M374.3 -389.5H526.3M374.3 -351.5H526.3M374.3 -340.1H526.3M374.3 -302.1H526.3M374.3 -290.7H526.3M374.3 -252.7H526.3M374.3 -241.3H526.3M374.3 -203.3H526.3M374.3 -191.9H526.3M374.3 -153.9H526.3M374.3 -142.5H526.3M374.3 -104.5H526.3M374.3 -93.1H526.3M374.3 -55.1H526.3M374.3 -43.7H526.3M374.3 -5.7H526.3M374.3 5.7H526.3M374.3 43.7H526.3M374.3 55.1H526.3M374.3 93.1H526.3M374.3 104.5H526.3M374.3 142.5H526.3M374.3 153.9H526.3M374.3 191.9H526.3M374.3 203.3H526.3M374.3 241.3H526.3M374.3 252.7H526.3M374.3 290.7H526.3M374.3 302.1H526.3M374.3 340.1H526.3M374.3 351.5H526.3M374.3 389.5H526.3M374.3 400.9H526.3M374.3 438.9H526.3M374.3 450.3H526.3M374.3 488.3H526.3M374.3 499.7H526.3M374.3 537.7H526.3M545.3 -340.1H697.3M545.3 -302.1H697.3M545.3 -290.7H697.3M545.3 -252.7H697.3M545.3 -241.3H697.3M545.3 -203.3H697.3M545.3 -191.9H697.3M545.3 -153.9H697.3M545.3 -142.5H697.3M545.3 -104.5H697.3M545.3 -93.1H697.3M545.3 -55.1H697.3M545.3 -43.7H697.3M545.3 -5.7H697.3M545.3 5.7H697.3M545.3 43.7H697.3M545.3 55.1H697.3M545.3 93.1H697.3M545.3 104.5H697.3M545.3 142.5H697.3M545.3 153.9H697.3M545.3 191.9H697.3M545.3 203.3H697.3M545.3 241.3H697.3M545.3 252.7H697.3M545.3 290.7H697.3M545.3 302.1H697.3M545.3 340.1H697.3","heavy":"M-651.7 -389.5V-351.5M-532 -389.5V-351.5M-651.7 -340.1V-302.1M-532 -340.1V-302.1M-651.7 -290.7V-252.7M-532 -290.7V-252.7M-651.7 -241.3V-203.3M-532 -241.3V-203.3M-651.7 -191.9V-153.9M-532 -191.9V-153.9M-651.7 -142.5V-104.5M-532 -142.5V-104.5M-651.7 -93.1V-55.1M-532 -93.1V-55.1M-651.7 -43.7V-5.7M-532 -43.7V-5.7M-651.7 5.7V43.7M-532 5.7V43.7M-651.7 55.1V93.1M-532 55.1V93.1M-651.7 104.5V142.5M-532 104.5V142.5M-651.7 153.9V191.9M-532 153.9V191.9M-651.7 203.3V241.3M-532 203.3V241.3M-651.7 252.7V290.7M-532 252.7V290.7M-651.7 302.1V340.1M-532 302.1V340.1M-651.7 351.5V389.5M-532 351.5V389.5M-513 -537.7V-499.7M-397.1 -537.7V-499.7M-513 -488.3V-450.3M-397.1 -488.3V-450.3M-513 -438.9V-400.9M-397.1 -438.9V-400.9M-513 -389.5V-351.5M-397.1 -389.5V-351.5M-513 -340.1V-302.1M-397.1 -340.1V-302.1M-513 -290.7V-252.7M-397.1 -290.7V-252.7M-513 -241.3V-203.3M-397.1 -241.3V-203.3M-513 -191.9V-153.9M-397.1 -191.9V-153.9M-513 -142.5V-104.5M-397.1 -142.5V-104.5M-513 -93.1V-55.1M-397.1 -93.1V-55.1M-513 -43.7V-5.7M-397.1 -43.7V-5.7M-513 5.7V43.7M-397.1 5.7V43.7M-513 55.1V93.1M-397.1 55.1V93.1M-513 104.5V142.5M-397.1 104.5V142.5M-513 153.9V191.9M-397.1 153.9V191.9M-513 203.3V241.3M-397.1 203.3V241.3M-513 252.7V290.7M-397.1 252.7V290.7M-513 302.1V340.1M-397.1 302.1V340.1M-513 351.5V389.5M-397.1 351.5V389.5M-513 400.9V438.9M-397.1 400.9V438.9M-513 450.3V488.3M-397.1 450.3V488.3M-513 499.7V537.7M-397.1 499.7V537.7M-378.1 -636.5V-598.5M-203.3 -636.5V-598.5M-378.1 -587.1V-549.1M-203.3 -587.1V-549.1M-378.1 -537.7V-499.7M-203.3 -537.7V-499.7M-378.1 -488.3V-450.3M-203.3 -488.3V-450.3M-378.1 -438.9V-400.9M-203.3 -438.9V-400.9M-378.1 -389.5V-351.5M-203.3 -389.5V-351.5M-378.1 -340.1V-302.1M-203.3 -340.1V-302.1M-378.1 -290.7V-252.7M-203.3 -290.7V-252.7M-378.1 -241.3V-203.3M-203.3 -241.3V-203.3M-378.1 -191.9V-153.9M-203.3 -191.9V-153.9M-378.1 -142.5V-104.5M-203.3 -142.5V-104.5M-378.1 -93.1V-55.1M-203.3 -93.1V-55.1M-378.1 -43.7V-5.7M-203.3 -43.7V-5.7M-378.1 5.7V43.7M-203.3 5.7V43.7M-378.1 55.1V93.1M-203.3 55.1V93.1M-378.1 104.5V142.5M-203.3 104.5V142.5M-378.1 153.9V191.9M-203.3 153.9V191.9M-378.1 203.3V241.3M-203.3 203.3V241.3M-378.1 252.7V290.7M-203.3 252.7V290.7M-378.1 302.1V340.1M-203.3 302.1V340.1M-378.1 351.5V389.5M-203.3 351.5V389.5M-378.1 400.9V438.9M-203.3 400.9V438.9M-378.1 450.3V488.3M-203.3 450.3V488.3M-378.1 499.7V537.7M-203.3 499.7V537.7M-378.1 549.1V587.1M-203.3 549.1V587.1M-378.1 598.5V636.5M-203.3 598.5V636.5M-184.3 -685.9V-647.9M-9.5 -685.9V-647.9M-184.3 -636.5V-598.5M-9.5 -636.5V-598.5M-184.3 -587.1V-549.1M-9.5 -587.1V-549.1M-184.3 -537.7V-499.7M-9.5 -537.7V-499.7M-184.3 -488.3V-450.3M-9.5 -488.3V-450.3M-184.3 -438.9V-400.9M-9.5 -438.9V-400.9M-184.3 -389.5V-351.5M-9.5 -389.5V-351.5M-184.3 -340.1V-302.1M-9.5 -340.1V-302.1M-184.3 -290.7V-252.7M-9.5 -290.7V-252.7M-184.3 -241.3V-203.3M-9.5 -241.3V-203.3M-184.3 -191.9V-153.9M-9.5 -191.9V-153.9M-184.3 -142.5V-104.5M-9.5 -142.5V-104.5M-184.3 -93.1V-55.1M-9.5 -93.1V-55.1M-184.3 -43.7V-5.7M-9.5 -43.7V-5.7M-184.3 5.7V43.7M-9.5 5.7V43.7M-184.3 55.1V93.1M-9.5 55.1V93.1M-184.3 104.5V142.5M-9.5 104.5V142.5M-184.3 153.9V191.9M-9.5 153.9V191.9M-184.3 203.3V241.3M-9.5 203.3V241.3M-184.3 252.7V290.7M-9.5 252.7V290.7M-184.3 302.1V340.1M-9.5 302.1V340.1M-184.3 351.5V389.5M-9.5 351.5V389.5M-184.3 400.9V438.9M-9.5 400.9V438.9M-184.3 450.3V488.3M-9.5 450.3V488.3M-184.3 499.7V537.7M-9.5 499.7V537.7M-184.3 549.1V587.1M-9.5 549.1V587.1M-184.3 598.5V636.5M-9.5 598.5V636.5M9.5 -685.9V-647.9M184.3 -685.9V-647.9M9.5 -636.5V-598.5M184.3 -636.5V-598.5M9.5 -587.1V-549.1M184.3 -587.1V-549.1M9.5 -537.7V-499.7M184.3 -537.7V-499.7M9.5 -488.3V-450.3M184.3 -488.3V-450.3M9.5 -438.9V-400.9M184.3 -438.9V-400.9M9.5 -389.5V-351.5M184.3 -389.5V-351.5M9.5 -340.1V-302.1M184.3 -340.1V-302.1M9.5 -290.7V-252.7M184.3 -290.7V-252.7M9.5 -241.3V-203.3M184.3 -241.3V-203.3M9.5 -191.9V-153.9M184.3 -191.9V-153.9M9.5 -142.5V-104.5M184.3 -142.5V-104.5M9.5 -93.1V-55.1M184.3 -93.1V-55.1M9.5 -43.7V-5.7M184.3 -43.7V-5.7M9.5 5.7V43.7M184.3 5.7V43.7M9.5 55.1V93.1M184.3 55.1V93.1M9.5 104.5V142.5M184.3 104.5V142.5M9.5 153.9V191.9M184.3 153.9V191.9M9.5 203.3V241.3M184.3 203.3V241.3M9.5 252.7V290.7M184.3 252.7V290.7M9.5 302.1V340.1M184.3 302.1V340.1M9.5 351.5V389.5M184.3 351.5V389.5M9.5 400.9V438.9M184.3 400.9V438.9M9.5 450.3V488.3M184.3 450.3V488.3M9.5 499.7V537.7M184.3 499.7V537.7M9.5 549.1V587.1M184.3 549.1V587.1M9.5 598.5V636.5M184.3 598.5V636.5M203.3 -636.5V-598.5M355.3 -636.5V-598.5M203.3 -587.1V-549.1M355.3 -587.1V-549.1M203.3 -537.7V-499.7M355.3 -537.7V-499.7M203.3 -488.3V-450.3M355.3 -488.3V-450.3M203.3 -438.9V-400.9M355.3 -438.9V-400.9M203.3 -389.5V-351.5M355.3 -389.5V-351.5M203.3 -340.1V-302.1M355.3 -340.1V-302.1M203.3 -290.7V-252.7M355.3 -290.7V-252.7M203.3 -241.3V-203.3M355.3 -241.3V-203.3M203.3 -191.9V-153.9M355.3 -191.9V-153.9M203.3 -142.5V-104.5M355.3 -142.5V-104.5M203.3 -93.1V-55.1M355.3 -93.1V-55.1M203.3 -43.7V-5.7M355.3 -43.7V-5.7M203.3 5.7V43.7M355.3 5.7V43.7M203.3 55.1V93.1M355.3 55.1V93.1M203.3 104.5V142.5M355.3 104.5V142.5M203.3 153.9V191.9M355.3 153.9V191.9M203.3 203.3V241.3M355.3 203.3V241.3M203.3 252.7V290.7M355.3 252.7V290.7M203.3 302.1V340.1M355.3 302.1V340.1M203.3 351.5V389.5M355.3 351.5V389.5M203.3 400.9V438.9M355.3 400.9V438.9M203.3 450.3V488.3M355.3 450.3V488.3M203.3 499.7V537.7M355.3 499.7V537.7M203.3 549.1V587.1M355.3 549.1V587.1M203.3 598.5V636.5M355.3 598.5V636.5M374.3 -537.7V-499.7M526.3 -537.7V-499.7M374.3 -488.3V-450.3M526.3 -488.3V-450.3M374.3 -438.9V-400.9M526.3 -438.9V-400.9M374.3 -389.5V-351.5M526.3 -389.5V-351.5M374.3 -340.1V-302.1M526.3 -340.1V-302.1M374.3 -290.7V-252.7M526.3 -290.7V-252.7M374.3 -241.3V-203.3M526.3 -241.3V-203.3M374.3 -191.9V-153.9M526.3 -191.9V-153.9M374.3 -142.5V-104.5M526.3 -142.5V-104.5M374.3 -93.1V-55.1M526.3 -93.1V-55.1M374.3 -43.7V-5.7M526.3 -43.7V-5.7M374.3 5.7V43.7M526.3 5.7V43.7M374.3 55.1V93.1M526.3 55.1V93.1M374.3 104.5V142.5M526.3 104.5V142.5M374.3 153.9V191.9M526.3 153.9V191.9M374.3 203.3V241.3M526.3 203.3V241.3M374.3 252.7V290.7M526.3 252.7V290.7M374.3 302.1V340.1M526.3 302.1V340.1M374.3 351.5V389.5M526.3 351.5V389.5M374.3 400.9V438.9M526.3 400.9V438.9M374.3 450.3V488.3M526.3 450.3V488.3M374.3 499.7V537.7M526.3 499.7V537.7M545.3 -340.1V-302.1M697.3 -340.1V-302.1M545.3 -290.7V-252.7M697.3 -290.7V-252.7M545.3 -241.3V-203.3M697.3 -241.3V-203.3M545.3 -191.9V-153.9M697.3 -191.9V-153.9M545.3 -142.5V-104.5M697.3 -142.5V-104.5M545.3 -93.1V-55.1M697.3 -93.1V-55.1M545.3 -43.7V-5.7M697.3 -43.7V-5.7M545.3 5.7V43.7M697.3 5.7V43.7M545.3 55.1V93.1M697.3 55.1V93.1M545.3 104.5V142.5M697.3 104.5V142.5M545.3 153.9V191.9M697.3 153.9V191.9M545.3 203.3V241.3M697.3 203.3V241.3M545.3 252.7V290.7M697.3 252.7V290.7M545.3 302.1V340.1M697.3 302.1V340.1","north":{"trueNorth":"M500 430L500 180","trueNorthHead":"M495 194L500 180L505 194","gridNorth":"M500 430L621.2 211.3","gridNorthHead":"M610 221.1L621.2 211.3L618.8 226","arc":"M500 298A132 132 0 0 1 564 314.6","tips":{"trueNorth":[500,180],"gridNorth":[621.2,211.3]},"arcMid":[536.6,288.7],"arcLen":66.8}} as const;
// </grid1811>

const G = GEN as unknown as {
  row: { w: number; h: number };
  bays: string;
  outline: readonly number[];
  cloud: readonly number[];
  cloudBox: readonly [number, number, number, number];
  view: { w: number; h: number };
  vertex: { x: number; y: number };
  angle: number;
  fieldR: number;
  thin: string;
  heavy: string;
};

/** The morph: straight outline (m = 0) → HOLD cloud (m = 1), same 24-cubic structure. */
function morphPath(m: number): string {
  const a = G.outline;
  const b = G.cloud;
  const f = (i: number) => Math.round(lerp(a[i]!, b[i]!, m) * 10) / 10;
  let d = `M${f(0)} ${f(1)}`;
  for (let i = 2; i < a.length; i += 6) d += `C${f(i)} ${f(i + 1)} ${f(i + 2)} ${f(i + 3)} ${f(i + 4)} ${f(i + 5)}`;
  return `${d}Z`;
}

const VX = `${(G.vertex.x / G.view.w) * 100}%`;
const VY = `${(G.vertex.y / G.view.h) * 100}%`;
/** clip-path circle() radius (in % of the reference length) that reaches the farthest frame corner */
const REVEAL_FULL = (() => {
  const { w, h } = G.view;
  const ref = Math.sqrt((w * w + h * h) / 2);
  const far = Math.hypot(Math.max(G.vertex.x, w - G.vertex.x), Math.max(G.vertex.y, h - G.vertex.y));
  return (far / ref) * 100 + 0.5;
})();

const CB = G.cloudBox;
const CLOUD_BOX_STYLE: CSSProperties = {
  left: `${(CB[0] / G.row.w) * 100}%`,
  top: `${(CB[1] / G.row.h) * 100}%`,
  width: `${((CB[2] - CB[0]) / G.row.w) * 100}%`,
  height: `${((CB[3] - CB[1]) / G.row.h) * 100}%`,
};

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

export default function A200Context() {
  const live = useLive();
  const trackRef = useRef<HTMLDivElement>(null);
  const pinRef = useRef<HTMLDivElement>(null);
  const rowRef = useRef<HTMLDivElement>(null);
  const posterRef = useRef<HTMLDivElement>(null);
  const baysRef = useRef<SVGPathElement>(null);
  const labelRef = useRef<HTMLParagraphElement>(null);
  const cloudRef = useRef<HTMLDivElement>(null);
  const cloudPathRef = useRef<SVGPathElement>(null);
  const cloudTextRef = useRef<HTMLDivElement>(null);
  const holdRef = useRef<HTMLDivElement>(null);
  const gridRef = useRef<HTMLDivElement>(null);
  const fieldRef = useRef<HTMLDivElement>(null);
  const boxRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLDivElement>(null);
  const frameRefs = useRef<Array<SVGPathElement | null>>([]);
  const geo = useRef<{ C: Rect; T: Rect | null; phone: boolean } | null>(null);
  const pulsed = useRef(false);
  const lastP = useRef(-1);
  const focused = useRef(false);

  const p = useStageProgress(trackRef);
  const boxW = useWidth(boxRef);
  // north arrow length scales with the drawing; labels at the tips only where they fit
  const L = boxW ? Math.max(70, Math.min(210, Math.round(boxW * 0.25))) : 186;
  const tipLabels = boxW === 0 || boxW >= 560;
  // the frame's own px size, so its stroke is 1 px and its dash (the draw-on) measures true lengths
  const FW = boxW || 1000;
  const FH = Math.round(FW * 0.8 * 10) / 10;

  /** Cache the FLIP geometry (pin-relative px; the pin is stuck at the viewport top while it runs). */
  const measure = useCallback(() => {
    const pin = pinRef.current;
    const row = rowRef.current;
    if (!pin || !row) return;
    const phone = window.matchMedia('(max-width: 767px)').matches;
    const pr = pin.getBoundingClientRect();
    const rr = row.getBoundingClientRect();
    const k = rr.width / G.row.w;
    const C: Rect = {
      x: rr.left - pr.left + CB[0] * k,
      y: rr.top - pr.top + CB[1] * k,
      w: (CB[2] - CB[0]) * k,
      h: (CB[3] - CB[1]) * k,
    };
    let T: Rect | null = null;
    // phone: the row sits on the drawing's centre (the box is laid out, hidden, before the grid draws)
    if (phone) {
      const bx = boxRef.current?.getBoundingClientRect();
      const st = row.offsetParent as HTMLElement | null;
      if (bx && bx.height && st) {
        const sr = st.getBoundingClientRect();
        row.style.top = `${Math.round(bx.top - sr.top + bx.height / 2)}px`;
      }
    } else row.style.removeProperty('top');
    const rr2 = row.getBoundingClientRect();
    C.y = rr2.top - pr.top + CB[1] * k;
    if (phone) {
      const svg = holdRef.current?.querySelector('svg');
      const hr = svg?.getBoundingClientRect();
      if (hr && hr.width) T = { x: hr.left - pr.left, y: hr.top - pr.top, w: hr.width, h: hr.height };
    } else {
      const cell = titleStrip.getCell('venue');
      const mark = cell?.querySelector<SVGElement>('.hold-mark') ?? cell;
      const r = mark?.getBoundingClientRect();
      // the pin is sticky at top: 0 while the fly runs, so viewport y == pin-relative y
      if (r && r.width) T = { x: r.left - pr.left, y: r.top, w: r.width, h: r.height };
    }
    geo.current = { C, T, phone };
  }, []);

  const apply = useCallback(
    (v: number) => {
      const s = (a: number, b: number) => segment(v, a, b);
      // ---- 0–0.12: poster -> pencil outline
      const posterOut = s(0.02, 0.1);
      if (posterRef.current) {
        posterRef.current.style.opacity = String(1 - posterOut);
        posterRef.current.toggleAttribute('data-off', v >= 0.1);
      }
      if (baysRef.current) baysRef.current.style.opacity = String(s(0.0, 0.06) * (1 - s(0.13, 0.19)));
      // the label hands over to the cloud's tag with an overlap, so a readable line is always on screen
      if (labelRef.current) labelRef.current.style.opacity = String(s(0.04, 0.09) * (1 - s(0.16, 0.19)));
      // ---- 0.12–0.20: outline -> cloud, tag in by 0.20
      const m = settleEase(s(0.12, 0.2));
      const tint = s(0.12, 0.18);
      const path = cloudPathRef.current;
      if (path) {
        path.setAttribute('d', morphPath(m));
        path.style.stroke = mixHex(PAL.pencil, PAL.orange, tint);
        path.style.strokeWidth = String(lerp(1, 1.5, tint));
        path.style.opacity = String(s(0.0, 0.06));
      }
      if (cloudTextRef.current) cloudTextRef.current.style.opacity = String(s(0.13, 0.18) * (1 - s(0.46, 0.48)));
      // ---- 0.40–0.50: lift and fly (FLIP)
      const lift = s(0.4, 0.42);
      // scroll-mapped, so the flight eases in and out (DRAW); SETTLE's steep start would launch the cloud
      // on the first wheel tick. The landing still settles: the last fifth of the path barely moves.
      const fly = drawEase(s(0.41, 0.49));
      const cloud = cloudRef.current;
      const g = geo.current;
      if (cloud) {
        cloud.style.setProperty('--lift', `${lerp(2, 6, lift)}px`);
        let tf = '';
        if (g?.T && fly > 0) {
          const { C, T } = g;
          const sEnd = Math.min(T.w / C.w, T.h / C.h);
          const sc = Math.pow(sEnd, fly) * (1 + 0.02 * lift * (1 - fly));
          const cx = lerp(C.x + C.w / 2, T.x + T.w / 2, fly);
          const cy = lerp(C.y + C.h / 2, T.y + T.h / 2, fly);
          tf = `translate(${cx - C.x - (sc * C.w) / 2}px, ${cy - C.y - (sc * C.h) / 2}px) scale(${sc})`;
        } else if (lift > 0) {
          const sc = 1 + 0.02 * lift;
          tf = `translate(${(C0w(g) * (1 - sc)) / 2}px, ${(C0h(g) * (1 - sc)) / 2}px) scale(${sc})`;
        }
        cloud.style.transform = tf;
        // it hands over to the strip's own mark (desktop) or to the static tag under the legend (phone)
        cloud.style.opacity = String(1 - s(0.475, 0.5));
      }
      if (holdRef.current) holdRef.current.style.opacity = g?.phone ? String(s(0.46, 0.5)) : '';
      if (v >= 0.495 && lastP.current < 0.495 && !pulsed.current && g && !g.phone) {
        pulsed.current = true;
        titleStrip.pulse('venue');
      }
      if (v < 0.4) pulsed.current = false;
      // ---- 0.40–0.85: the 1811 grid, a separate drawing; never an empty frame
      gridRef.current?.toggleAttribute('data-on', v >= 0.4);
      gridRef.current?.toggleAttribute('data-cap', v >= 0.45);
      const frame = drawEase(s(0.4, 0.52));
      frameRefs.current.forEach((el) => el?.style.setProperty('stroke-dashoffset', String(1 - frame)));
      const reveal = drawEase(s(0.42, 0.8));
      if (fieldRef.current) fieldRef.current.style.clipPath = `circle(${(reveal * REVEAL_FULL).toFixed(2)}% at ${VX} ${VY})`;
      const box = boxRef.current;
      if (box) {
        box.style.setProperty('--tn', String(drawEase(s(0.7, 0.8))));
        box.style.setProperty('--tn-ink', String(s(0.77, 0.81)));
        box.style.setProperty('--gn', String(drawEase(s(0.74, 0.84))));
        box.style.setProperty('--gn-ink', String(s(0.81, 0.85)));
        box.style.setProperty('--arc', String(drawEase(s(0.78, 0.86))));
        box.style.setProperty('--arc-ink', String(s(0.83, 0.86)));
      }
      // ---- 0.55: H2 and body print; 0.85: the statement
      textRef.current?.classList.toggle('is-in', v >= 0.55 || focused.current);
      textRef.current?.classList.toggle('is-st', v >= 0.85 || focused.current);
      lastP.current = v;
    },
    [],
  );

  // live: drive everything from p; static: clear inline styles back to the CSS end state
  useEffect(() => {
    if (!live) {
      // back to the CSS end state (only the properties apply() writes; React owns the rest)
      const clear = (el: HTMLElement | SVGElement | null, props: string[]) => props.forEach((k) => el?.style.removeProperty(k));
      clear(posterRef.current, ['opacity']);
      posterRef.current?.removeAttribute('data-off');
      clear(baysRef.current, ['opacity']);
      clear(labelRef.current, ['opacity']);
      clear(cloudPathRef.current, ['stroke', 'stroke-width', 'opacity']);
      clear(cloudTextRef.current, ['opacity']);
      clear(cloudRef.current, ['--lift', 'transform', 'opacity']);
      clear(holdRef.current, ['opacity']);
      clear(fieldRef.current, ['clip-path']);
      clear(boxRef.current, ['--tn', '--tn-ink', '--gn', '--gn-ink', '--arc', '--arc-ink']);
      frameRefs.current.forEach((el) => el?.style.removeProperty('stroke-dashoffset'));
      textRef.current?.classList.add('is-in', 'is-st');
      gridRef.current?.setAttribute('data-on', '');
      gridRef.current?.setAttribute('data-cap', '');
      return;
    }
    measure();
    apply(p.get());
    const offP = p.on('change', apply);
    const offL = onLayout(() => {
      measure();
      apply(p.get());
    });
    return () => {
      offP();
      offL();
    };
  }, [live, p, apply, measure]);

  // a jump (INDEX, CTA) on a two-column desktop lands on the finished frame, p = 0.88 (F-043, F-015): the
  // H2, body and statement printed beside the drawn grid. Elsewhere the text follows the pin, so the default
  // H2 landing applies.
  const wide = useMediaQuery('(min-width: 1024px)');
  useEffect(() => {
    const sec = trackRef.current?.closest<HTMLElement>('[data-sheet]');
    if (!sec) return;
    if (live && wide) sec.dataset.land = '88';
    else delete sec.dataset.land;
    return () => {
      delete sec.dataset.land;
    };
  }, [live, wide]);

  // ?capture scene 'context': t (0..6 s) maps linearly onto the stage progress
  useEffect(() => {
    const DURATION = 6;
    return registerCaptureScene('context', {
      duration: DURATION,
      async seek(t) {
        const track = trackRef.current;
        if (!track) return;
        const r = track.getBoundingClientRect();
        const top = r.top + window.scrollY;
        const span = Math.max(1, r.height - window.innerHeight);
        window.scrollTo(0, top + (t / DURATION) * span);
        await frames(2);
        measure();
        apply(p.get());
        await frames(1);
      },
    });
  }, [p, apply, measure]);

  const body = a200Body();
  const gridLabel = A200.labels.grid;

  return (
    <div className="a200" data-live={live ? '' : undefined}>
      <div className="a200-track" ref={trackRef}>
        <div className="a200-pin" ref={pinRef}>
          <div className="a200-stage">
            <SheetTag id="A-200" className="a200-tag" />

            {/* phase 1–3: the row poster, its pencil outline and the HOLD cloud (live only) */}
            <div className="a200-row" ref={rowRef}>
              <p className="a200-bays-label t-label" ref={labelRef} aria-hidden="true">
                {A200.labels.bays}
              </p>
              <div className="a200-poster" ref={posterRef}>
                <ViewTitle id="a200-poster">
                  <Picture id="arena-poster" loading="lazy" />
                </ViewTitle>
              </div>
              <svg
                className="a200-bays"
                viewBox={`0 0 ${G.row.w} ${G.row.h}`}
                preserveAspectRatio="none"
                aria-hidden="true"
                focusable="false"
              >
                <path ref={baysRef} d={G.bays} />
              </svg>
              <div className="a200-cloud" ref={cloudRef} style={CLOUD_BOX_STYLE} aria-hidden="true">
                <svg viewBox={`${CB[0]} ${CB[1]} ${CB[2] - CB[0]} ${CB[3] - CB[1]}`} focusable="false">
                  <path ref={cloudPathRef} d={morphPath(0)} />
                </svg>
                <div className="a200-cloud-text" ref={cloudTextRef}>
                  <span className="a200-cloud-head">{A200.hold.head}</span>
                  <span className="a200-cloud-tail">{A200.hold.tail}</span>
                </div>
              </div>
            </div>

            {/* 0.40–0.85: the 1811 grid, a separate history diagram */}
            <div className="a200-grid" ref={gridRef}>
              <ViewTitle id="a200-drawing">
                <div className="a200-box" ref={boxRef} role="img" aria-label={A200.gridAlt}>
                  <div className="a200-field" ref={fieldRef}>
                    <svg viewBox={`0 0 ${G.view.w} ${G.view.h}`} aria-hidden="true" focusable="false">
                      <g transform={`translate(${G.vertex.x} ${G.vertex.y}) rotate(${G.angle})`}>
                        <path className="a200-streets" d={G.thin} />
                        <path className="a200-avenues" d={G.heavy} />
                      </g>
                    </svg>
                  </div>
                  <div className="a200-compass" aria-hidden="true" style={{ left: VX, top: VY }}>
                    {/* F-088: a slab-black halo under both arrows and the arc knocks the grid out beneath them */}
                    <NorthArrow className="a200-tn a200-halo" angle={0} length={L} />
                    <NorthArrow className="a200-gn a200-halo" angle={G.angle} length={L} />
                    <AngleArc className="a200-arc a200-halo" from={0} to={G.angle} radius={Math.round(L * 0.56)} extent={L + 70} />
                    <NorthArrow className="a200-tn" angle={0} length={L} label={tipLabels ? A200.labels.trueNorth : undefined} />
                    <NorthArrow className="a200-gn" angle={G.angle} length={L} label={tipLabels ? gridLabel : undefined} />
                    <AngleArc
                      className="a200-arc"
                      from={0}
                      to={G.angle}
                      radius={Math.round(L * 0.56)}
                      extent={L + 70}
                      label={A200.labels.angle}
                    />
                  </div>
                </div>
                {/* the frame strokes on from its top-right corner with the first lines (no empty box) */}
                <svg className="a200-framedraw" viewBox={`0 0 ${FW} ${FH}`} preserveAspectRatio="none" aria-hidden="true" focusable="false">
                  {[`M${FW - 0.5} 0.5H0.5V${FH - 0.5}`, `M${FW - 0.5} 0.5V${FH - 0.5}H0.5`].map((d, i) => (
                    <path
                      key={d}
                      ref={(el) => {
                        frameRefs.current[i] = el;
                      }}
                      d={d}
                      pathLength={1}
                    />
                  ))}
                </svg>
              </ViewTitle>
              {!tipLabels ? (
                <p className="a200-legend t-label" aria-hidden="true">
                  <span>↑ {A200.labels.trueNorth}</span>
                  <span>↗ {gridLabel}</span>
                </p>
              ) : null}
            </div>

            {/* the HOLD tag on its own: static layouts, and the phone's settled tag under the legend */}
            <div className="a200-hold" ref={holdRef}>
              <HoldCloud width={296} height={56} tag={A200.hold.head} title={A200.hold.cloudAlt}>
                <span className="a200-hold-body">{A200.hold.tail}</span>
              </HoldCloud>
            </div>
          </div>
        </div>
      </div>

      <div className="a200-text print-in" ref={textRef}>
        <h2
          className="t-h2-statement a200-h2"
          onFocus={() => {
            // a CTA / INDEX jump focuses the H2 before the stage has printed it: show it at once
            focused.current = true;
            textRef.current?.classList.add('is-in', 'is-st');
          }}
          onBlur={() => {
            focused.current = false;
          }}
        >
          {A200.h2}
        </h2>
        <p className="t-body a200-body">{body}</p>
        <p className="a200-statement">{A200.statement}</p>
      </div>
    </div>
  );
}

function C0w(g: { C: Rect } | null): number {
  return g ? g.C.w : 0;
}
function C0h(g: { C: Rect } | null): number {
  return g ? g.C.h : 0;
}
